name: Publish to GitHub Packages

on:
    push:
        branches:
            - main

jobs:
    publish_to_github_packages:
        name: Publish to GitHub Packages
        runs-on: ubuntu-latest

        environment: workflows

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "16.x"
                  registry-url: "https://npm.pkg.github.com/"

            - uses: pnpm/action-setup@v2.0.1
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 8
                  run_install: false

            - name: Install Deps
              run: pnpm i

            - name: Test
              run: pnpm t

            - name: Build
              run: pnpm build

            - name: Set GitHub Token
              run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

            - name: Publish New Version
              run: pnpm publish --registry=https://npm.pkg.github.com/
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
